### ISSUE TITLE
add ability to get raw (plaintext) values without yaml markup

### ISSUE THREAD

**Issue by spikegrobstein** [mikefarah/yq#200] opened 2019-01-10 18:37 UTC
`jq` has an option that will output "raw" data (`-r`), but it doesn't seem that `yq` has this. This is used for cases where one just wants the result without the yaml syntax. For example:

```yaml
items:
  - id: foo
     name: hotdog
  - id: bar
    name: hamburger
```

```console
$ yq r data.yml 'items[*].id'
- foo
- bar
```

What I'd like is something like:

```console
$ yq r data.yml 'items[*].id' --raw
foo
bar
```

this makes it easier to integrate `yq` in my shell scripts when reading values out of yaml files without having to do any post processing. Right now, I'm doing the following to get the same effect, which works, but it would be nice to not have to flip over to `jq` to do this:

    yq r data.yml -j | jq -r 'items[].id'

**Comment by mikefarah** [comment] 2019-01-20 09:49
Dupe of #107

**Comment by mikefarah** [comment] 2019-01-20 09:51
Oops no it isnt! Just realised this is read not write

**Comment by mikefarah** [comment] 2020-02-01 02:27
Done! Checkout out https://github.com/mikefarah/yq/releases/tag/3.0.1

**Comment by mikefarah** [comment] 2020-02-01 02:28
(its the default behaviour when matching scalar values are found)

**Closed by mikefarah** 2020-02-01 02:27 UTC
Labels: enhancement

**Comment by ashish-amarnath** [comment] 2021-07-08 22:38
@mikefarah 
Can you please share examples of how to use this? Or can you link the PR/commit in which this was fixed?

**Comment by rfay** [comment] 2022-12-07 19:13
I also didn't understand how this was changed, or what the technique for this is. 

With 
```bash
echo -e "- one\n- two\n" | yq -r
```

I get 
```yaml
- one
- two
```

But I would like an option for the output to be

```
one
two
```

You seem to imply that you added this feature in 3.0.1, but it's not mentioned there and I haven't figured out how to use it.

Thanks for yq!

**Comment by mikefarah** [comment] 2022-12-07 23:19
Hey so v3 isn't supported anymore - I'm going to assume you're using v4:

with the example you have you need to:

```
echo -e "- one\n- two\n" | yq '.[]'
```

Basically this splats the array into its components, each of which being a string scalar. Otherwise you are printing the array itself.

**Comment by rfay** [comment] 2022-12-07 23:26
Thanks @mikefarah , just what I needed.
