### ISSUE TITLE
v4 multiply operator (merge) dropping object level anchors

### ISSUE THREAD

**Issue by nknotts** [mikefarah/yq#694] opened 2021-01-28 01:01 UTC
**Describe the bug**
When using the V4 yq multiply operator, any anchor associated with an object node appears to be dropped in the output.

Version of yq: 4.4.1
Operating system: macOS 11.1
Installed via: homebrew

**Input Yaml**

a.yml:
```yaml
foo: &foo-alias
  bar: &bar-alias baz
  a: &c-node
    b: &b-node c
```

b.yml:
```yaml
test: &test-alias
  node: &node-alias 1
```

**Command**

```
yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' a.yml b.yml
```

**Actual behavior**

```yaml
foo:
  bar: &bar-alias baz
  a:
    b: &b-node c
test:
  node: &node-alias 1
```

**Expected behavior**

```yaml
foo: &foo-alias
  bar: &bar-alias baz
  a: &c-node
    b: &b-node c
test: &test-alias
  node: &node-alias 1
```

**Additional context**
When using yq version 3.4.1 command `yq merge a.yml b.yml`, the expected behavior is generated

**Comment by mikefarah** [comment] 2021-02-02 22:15
Looks like this is related to: https://github.com/mikefarah/yq/issues/677

**Comment by mikefarah** [comment] 2021-02-10 10:46
Fixed in 4.5.1

**Closed by mikefarah** 2021-02-10 10:46 UTC
Labels: bug, v4

**Comment by nknotts** [comment] 2021-02-10 11:29
Confirmed! Thank you so much.

**Comment by spazworm** [comment] 2021-02-16 06:29
Confirmed that it's fixed for me too, muchas gracias

**Comment by styu99** [comment] 2021-07-19 19:27
Hey, I still seem to be running into this issue whenever I use the + (append) flag when merging

**Comment by styu99** [comment] 2021-07-19 20:30
I still seem to be having this issue when using the + (append) merge flag

**Input yaml**
a.yml:
```yaml
:test:
  :foo: &common
    - PROP_A
  :bar:
    - *common
    - TEST
```
b.yml:
```yaml
:test:
  :foo: &common
    - PROP_B
```
**Command**
`yq eval-all 'select(fileIndex == 0) *+ select(fileIndex == 1)' a.yml b.yml > c.yml`
**Actual output**
c.yml:
```yaml
:test:
  :foo:
    - PROP_A
    - PROP_B
  :bar:
    - *common
    - TEST
```
**Expected output**
c.yml:
```yaml
:test:
  :foo: &common
    - PROP_A
    - PROP_B
  :bar:
    - *common
    - TEST
```
