### ISSUE TITLE
Strings containing : are wrapped in single quote - sometimes

### ISSUE THREAD

**Issue by Carsten-Holbach** [mikefarah/yq#942] opened 2021-09-23 14:55 UTC
Hey!

I am trying to create a YAML document on the fly (tag settings for Datadog).

There, I need to put in strings into an array containing `:`. As I understand, values containing `:` need to be wrapped into `'` or `"`. However, I am getting a mixed result, see below.

Version of yq: 4.13.2
Operating system: Ubuntu 20.04.3 LTS on WSL2
Installed via: binary release

**Command**
The command you ran:
```
yq e -i '.tags[0] = "nuc_version:"' tags.yaml
yq e -i '.tags[1] = "nuc_model:"' tags.yaml
yq e -i '.tags[2] = "bios:"' tags.yaml
yq e -i '.tags[3] = "ubuntu:Ubuntu_20.04.3_LTS"' tags.yaml
yq e -i '.tags[4] = "kernel:5.10.16.3-microsoft-standard-WSL2"' tags.yaml
```

**Actual behavior**

```yaml
$ cat tags.yaml
tags:
  - 'nuc_version:'
  - 'nuc_model:'
  - 'bios:'
  - ubuntu:Ubuntu_20.04.3_LTS
  - kernel:5.10.16.3-microsoft-standard-WSL2
```

**Expected behavior**

```yaml
$ cat tags.yaml
tags:
  - 'nuc_version:'
  - 'nuc_model:'
  - 'bios:'
  - 'ubuntu:Ubuntu_20.04.3_LTS'
  - 'kernel:5.10.16.3-microsoft-standard-WSL2'
```

Please advise. Thank you.

**Comment by Carsten-Holbach** [comment] 2021-09-23 15:39
Addition:

**Comment by Carsten-Holbach** [comment] 2021-09-23 17:11
Addition:

**Comment by mikefarah** [comment] 2021-09-24 01:03
The underlying go-yaml parser automatically quotes strings if it thinks that if they didn't have quotes it would cause yaml parsing issues. What you done using `style=` is what I'd recommend if you want consistency when setting values that may automatically be quoted to avoid parsing issues.

Note that you can shorten your command to:

```bash
yq e -i '
  .tags = [ "nuc_version:", "nuc_model:", "bios:" ] |
  .tags[] style="double"
' tags.yaml
```

Closing this as it's intended behavior by go-yaml.

**Closed by mikefarah** 2021-09-24 01:03 UTC
Labels: bug, v4
