### ISSUE TITLE
When the yaml file has * then it will consume a lot of memory and cpu, also the process will be stuck there.

### ISSUE THREAD

**Issue by hlxwell** [mikefarah/yq#296] opened 2019-11-13 00:13 UTC
## Sample data
```
grpc:
  port: *grpc_server_port
auth:
  port: *http_server_port
```

## Command line
```
yq r -d'*' file.yaml
```

## Version
```
➜  ~ yq --version
yq version 2.4.1
```

## Result
The process is stuck there and CPU and Memory is soaring.

**Comment by apeschel** [comment] 2019-12-13 22:09
This looks like a duplicate of this issue: https://github.com/mikefarah/yq/issues/176

**Comment by mikefarah** [comment] 2019-12-16 09:11
Note - this isn't actually valid yaml, the * in front of the value is reserved for anchors, and there are no anchors with those names.

To get the document to work, you'll need to wrap the values in quotes.

That said, this is still a bug as it should just complain about a bad yaml and quit.

**Comment by mikefarah** [comment] 2020-01-31 02:24
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1

**Closed by mikefarah** 2020-01-31 02:24 UTC
Labels: bug, yaml-v3
