### ISSUE TITLE
Quotes removed

### ISSUE THREAD

**Issue by andye2004** [mikefarah/yq#254] opened 2019-06-29 02:37 UTC
I know there are a few of these quote type issues but I think my situation is a little different. I have a regex value in a valid yaml file and this regex MUST be quoted as it contains meta characters etc.

The line in the original document looks something like

```yaml
regex: "(?:^\/admin$|^\/admin\/.*$)"
```

With this regex double quoted yq fails with:-

`10:23:52 main [ERRO] Error reading document at index 0, yaml: found unknown escape character: yaml: found unknown escape character`

Modifying the original file so that it uses single quotes, e.g.

```yaml
regex: '(?:^\/admin$|^\/admin\/.*$)'
```

yq can now parse and modify the result as required, however the quotes around the regex are removed from the result, e.g.

```yaml
regex: (?:^\/admin$|^\/admin\/.*$|^\/frontend/.+$)
```

When I pass this to my upstream app (envoyproxy) things simply do not work as expected as the regex is no longer quoted.

This is likely more an issue with envoyproxy that with yq but is there any way that I can make yq preserve fields on output as they were read from the input document?

**Comment by vinayak-gadkari** [comment] 2019-06-29 03:05
Similar issue here. Can we preserve the quotes? If not, can we have an option to use quotes?

**Comment by andye2004** [comment] 2019-06-29 03:07
Apologies, just found this #19, seems to be a known issue. Real shame, this will prevent us from using yq.

**Comment by mikefarah** [comment] 2019-07-23 00:03
Yeah it requires a significant rewrite of yq to use the latest yaml library - just don't have time for that atm.

**Comment by mikefarah** [comment] 2019-07-23 00:04
closing as dupe of #19

**Closed by mikefarah** 2019-07-23 00:04 UTC
