### ISSUE TITLE
Deleting the only key/value leaves file with { }

### ISSUE THREAD

**Issue by kamzar1** [mikefarah/yq#544] opened 2020-09-20 07:35 UTC
yq version 3.3.2
Interactive deleting the only key/value pair leaves the file with curly brackets { }
Adding values to same file again, makes it json like and not yaml anymore.

add:
`$ yq w -i sample.yml things good`
cat sample.yml:
```
things: good
```
delete:
`yq d -i sample.yml things`
cat sample.yml:
`{}`

add again keys/values:

`$ yq w -i sample.yml otherthings better`
cat sample.yml
```
{otherthings: better}
```

**Comment by mikefarah** [comment] 2020-09-21 10:38
Closing as duplicate of https://github.com/mikefarah/yq/issues/493

**Closed by mikefarah** 2020-09-21 10:38 UTC
Labels: bug
