### ISSUE TITLE
Enable splat in delete paths

### ISSUE THREAD

**Issue by IBrokeYourCode** [mikefarah/yq#233] opened 2019-04-29 11:19 UTC
Sample YAML:
```
client1:
  info:
    contact: deleteThis
client2:
  info:
    contact: deleteThis
    relative:
        contact: keepThis
```
I'd like to delete the `contact` field from all clients, but not relatives.
I can read them like so:
`yq r file.yml *.*.contact`
But I can't delete them with this:
`yq d -i file.yml *.*.contact`

The file is opened, I can some indentation being changed, but the elements are not deleted. I can only delete them one by one by entering exact paths.

I wanted to try `yq w -d`, but it does not seem to work at all.

**Comment by mikefarah** [comment] 2019-04-29 23:14
Duplicate of https://github.com/mikefarah/yq/issues/175

**Closed by mikefarah** 2019-04-29 23:14 UTC
