### ISSUE TITLE
-f=extract flag only applied to first file

### ISSUE THREAD

**Issue by julianbarg** [mikefarah/yq#1187] opened 2022-04-17 18:35 UTC
**Describe the bug**
I tried extracting the front matter of multiple files with ```-f=extract```. yq would extract the front matter of the first document, and then ingest all following documents in their entirety, not just the front matter.

Version of yq: 4.24.2
Operating system: linux/Ubuntu 20.04
Installed via: snap

**Input Yaml**
data1.yml:
```yaml
---
key: test
---
There is some more content here.

```

data2.yml:
```yaml
---
key: test2
---
There is also more content here.

```

**Command**
```
yq -f=extract "." data*.yml
```

**Actual behavior**

```yaml
---
key: test
---
key: test2
---
There is also more content here.
```

**Expected behavior**

```yaml
---
key: test
---
key: test2
---
```

**Comment by mikefarah** [comment] 2022-04-27 04:52
This is a duplicate of https://github.com/mikefarah/yq/issues/1178

Snippet:
 yq only processes the first file for front matter. This ties in with how the write inplace flag works - it only writes to the first file. This makes more sense when working with 'process' instead of 'extract' - typically you'd want to write inplace the changes, and so you can only process one file at a time. To do what you need, you can use find with yq:

```
find -name  "*.md" -exec yq --front-matter="extract" {} \;
```

**Closed by mikefarah** 2022-04-27 04:52 UTC
Labels: bug, v4
