### ISSUE TITLE
Comments not preserved in output

### ISSUE THREAD

**Issue by kleht8** [mikefarah/yq#127] opened 2018-03-18 19:06 UTC
When updating values from source yaml comment lines are not preserved in output.

test.yaml:
```
# Test Comment
value: something
```
`yq w test.yaml value updated `

Outputs:
```
value: updated
```
Expected behavior would be to preserve comments from input.

**Comment by mikefarah** [comment] 2018-03-25 22:30
Closing as duplicate of https://github.com/mikefarah/yq/issues/19

**Closed by mikefarah** 2018-03-25 22:30 UTC
