### ISSUE TITLE
Error: 1:1: invalid input text "compare | (... |..."

### ISSUE THREAD

**Issue by hassanbsee2071** [mikefarah/yq#1842] opened 2023-10-25 10:43 UTC
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.35.2
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```
this: should really work
```

data2.yml:
```
but: it strangely didn't
```

**Command**
The command you ran:
```
 yq compare -P data1.yml data2.yml  users
```

**Actual behavior**

```yaml
Error: 1:1: invalid input text "compare | (... |..."
```

**Expected behavior**

```yaml
-this: should really work
+but: it strangely didn't
```

**Additional context**
When I execute I get below error. In version 3 it is working
Error: 1:1: invalid input text "compare | (... |..."

**Comment by teejaded** [comment] 2023-10-25 20:17
The compare command was removed in version 4.  This seems to be a duplicate of https://github.com/mikefarah/yq/issues/1272

**Comment by mikefarah** [comment] 2023-10-25 21:28
V3 worked quite differently from V4 - take a look here: https://mikefarah.gitbook.io/yq/upgrading-from-v3#comparing-yaml-files

**Closed by mikefarah** 2023-10-25 21:28 UTC
Labels: bug, v4
