### ISSUE TITLE
Trailing line spaces in string block changes to a quoted string

### ISSUE THREAD

**Issue by lazychanger** [mikefarah/yq#1282] opened 2022-07-27 08:35 UTC
**Describe the bug**
Why does yq compress the content ?

yq (https://github.com/mikefarah/yq/) version 4.23.1

**Input Yaml**
cm.yml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gwn-cm
  labels:
    app: gwn
    version: v1
data:
  config.yaml: |
    context: { }
    plugins:
      - name: github-autosync
        package: github-api
        version: latest
        config: |
          api: sync
          apiConfigs: 
            sync: 
              apiType: triggerRepositoryMirrorSyncConfig
              config: |
                accounts:
                  - account: admin
                    token: admin
                    condition: {{ eq .Request.Body.project.name "yunwei" }}
                repository: {}
                repositoryId: {{ printf "%.0f" .Request.Body.repository.id | quote }}
```
**Output Yaml**
data2.yml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gwn-cm
  labels:
    app: gwn
    version: v1
data:
  config.yaml: "context: { }\nplugins:\n  - name: github-autosync\n    package: github-api\n    version: latest\n    config: |\n      api: sync\n      apiConfigs: \n        sync: \n          apiType: triggerRepositoryMirrorSyncConfig\n          config: |\n            accounts:\n              - account: admin\n                token: admin\n                condition: {{ eq .Request.Body.project.name \"yunwei\" }}\n            repository: {}\n            repositoryId: {{ printf \"%.0f\" .Request.Body.repository.id | quote }}"
  newline.yaml: helloworld

```

**Command**
The command you ran:
```
yq -i ".data.\"newline.yaml\" = \"helloworld\"" data1.yml
```

**Comment by mikefarah** [comment] 2022-07-27 11:32
Just had a quick play with this - it seems to be caused by having trailing whitespace on the lines

```
apiConfigs: 
            sync: 
```

these both have trailing spaces - for some reason, the makes the yaml decoder wrap everything in quotes. 

If you change it to:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gwn-cm
  labels:
    app: gwn
    version: v1
data:
  config.yaml: |
    context: { }
    plugins:
      - name: github-autosync
        package: github-api
        version: latest
        config: |
          api: sync
          apiConfigs:
            sync:
              apiType: triggerRepositoryMirrorSyncConfig
              config: |
                accounts:
                  - account: admin
                    token: admin
                    condition: {{ eq .Request.Body.project.name "yunwei" }}
                repository: {}
                repositoryId: {{ printf "%.0f" .Request.Body.repository.id | quote }}
```
then it works

**Comment by mikefarah** [comment] 2022-07-27 11:33
(this is caused by the underlying go-yaml library)

**Comment by mikefarah** [comment] 2022-07-27 22:28
Duplicate of #1277

**Closed by mikefarah** 2022-07-27 22:28 UTC
Labels: bug, v4

**Comment by lazychanger** [comment] 2022-07-28 01:45
thanks, 

> Just had a quick play with this - it seems to be caused by having trailing whitespace on the lines
> 
> ```
> apiConfigs: 
>             sync: 
> ```
> 
> these both have trailing spaces - for some reason, the makes the yaml decoder wrap everything in quotes.
> 
> If you change it to:
> 
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: gwn-cm
>   labels:
>     app: gwn
>     version: v1
> data:
>   config.yaml: |
>     context: { }
>     plugins:
>       - name: github-autosync
>         package: github-api
>         version: latest
>         config: |
>           api: sync
>           apiConfigs:
>             sync:
>               apiType: triggerRepositoryMirrorSyncConfig
>               config: |
>                 accounts:
>                   - account: admin
>                     token: admin
>                     condition: {{ eq .Request.Body.project.name "yunwei" }}
>                 repository: {}
>                 repositoryId: {{ printf "%.0f" .Request.Body.repository.id | quote }}
> ```
> 
> then it works

Thank you very much. It works In yq
