### ISSUE TITLE
Support for writing null/undefined values?

### ISSUE THREAD

**Issue by gharris999** [mikefarah/yq#247] opened 2019-06-03 15:48 UTC
Yaml has a null/undefined type, usually represented by:

somekey: ~

see: https://yaml.org/type/null.html

If i need a yaml entry like:

bandInArtists: ~

..how do I write that using yq?  The tilde must be unquoted to be interpreted as null/undefined.

```
LPREF='bandInArtists'
yq n "$LPREF" \~
```
..yields..
```
bandInArtists: "~"
```
```
yq n "$LPREF" ""
```
..yields..
```
bandInArtists: ""
```
```
yq n "$LPREF"
```
..yields..
nothing / error.

**Comment by gharris999** [comment] 2019-06-03 16:10
Interestingly, 
```
yq n "$LPREF" nil
```
..yields..
```
bandInAritsts: nil
```
..which is getting close, (i.e., no quotes) except that most yaml parsers don't recognize nil as equaling ~ / null / undefined.

**Comment by gharris999** [comment] 2019-06-09 22:05
In general, I'm finding that I wished yq had a -r || --raw-output option like jq has.

If netplan requires this to connect to an open wifi network:
```
network:
  wifis:
    wlan0:
      access-points:
        test_ap: {}
```
..how would I write that using yq?  I.e. how would I write an unquoted {} ??

**Comment by mikefarah** [comment] 2019-06-10 12:20
Yeah this definitely needs to be fixed...when I find the time...or if someone raises a PR

Dupe of:

https://github.com/mikefarah/yq/issues/107

**Closed by mikefarah** 2019-06-10 12:20 UTC
