### ISSUE TITLE
Delete not working as expected

### ISSUE THREAD

**Issue by thatsk** [mikefarah/yq#799] opened 2021-04-28 16:02 UTC
Describe the bug

 del not working as expected.
A version of yq: 3.4.1
Operating system: Linux
Installed via: binary

**Input.yaml**
```
profile::generic_mdir::dirs::files:
  "/var/log/example1":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example2":
    ensure: file
    mode: "0644"
    content: |2
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
  "/var/log/example3":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example3":
    ensure: file
    mode: "0644"
    content: |2
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
docker::run_instance::instance:
  example2:
    image: 'servicedefination'
    depend_services:
      - consul
    volumes:
      - '/var/log/example2:/var/log/example2'
      - '/var/tmp:/var/tmp'
    net: host
    env:
      - CONSUL_TOKEN=%{hiera('consul.service_token')}
    stop_wait_time: 30
    remove_container_on_stop: false
  example1:
    image: 'servicedefination2'
    ensure: present
    depend_services:
      - consul
    volumes:
      - '/var/log/example1:/var/log/example1'
      - '/var/tmp:/var/tmp'
    net: host
    env:
      - CONSUL_TOKEN=%{hiera('service_token')}
    stop_wait_time: 30
    remove_container_on_stop: false
```
**command**
yq delete data.yaml 'docker::run_instance::instance.example2'

**Actual behaviour**
```
profile::generic_mdir::dirs::files:
  "/var/log/example1":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example2":
    ensure: file
    mode: "0644"
    content: |
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
  "/var/log/example3":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example3":
    ensure: file
    mode: "0644"
    content: |
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
docker::run_instance::instance:
  example1:
    image: 'servicedefination2'
    ensure: present
    depend_services:
      - consul
    volumes:
      - '/var/log/example1:/var/log/example1'
      - '/var/tmp:/var/tmp'
    net: host
    env:
      - CONSUL_TOKEN=%{hiera('service_token')}
    stop_wait_time: 30
    remove_container_on_stop: false
```
**Expected Behaviour**
```
profile::generic_mdir::dirs::files:
  "/var/log/example1":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example2":
    ensure: file
    mode: "0644"
    content: |2
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
  "/var/log/example3":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example3":
    ensure: file
    mode: "0644"
    content: |2
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
docker::run_instance::instance:
  example1:
    image: 'servicedefination2'
    ensure: present
    depend_services:
      - consul
    volumes:
      - '/var/log/example1:/var/log/example1'
      - '/var/tmp:/var/tmp'
    net: host
    env:
      - CONSUL_TOKEN=%{hiera('service_token')}
    stop_wait_time: 30
    remove_container_on_stop: false
```

**Comment by thatsk** [comment] 2021-04-28 16:05
why its touching profile key and removing 2 from content or also something has been changing don't know.

**Comment by thatsk** [comment] 2021-04-29 14:28
@mikefarah  am i doing something wrong?

**Comment by mikefarah** [comment] 2021-05-02 00:55
Sorry not clear what the issue is, can you please provide a concise clear example

**Comment by mikefarah** [comment] 2021-05-02 00:57
Note: 
- `yq` takes a best effort approach to preserve formatting, but some whitespace changes to happen
- version 3 is no longer supported - I recommend upgrading to v4 (though I will help out if I can)

**Comment by thatsk** [comment] 2021-05-02 04:53
Let me try it out and get back to you

**Comment by mikefarah** [comment] 2021-05-10 00:03
Closing this till more detail is received

**Closed by mikefarah** 2021-05-10 00:03 UTC
Labels: bug, v3

**Comment by thatsk** [comment] 2021-05-17 13:23
@mikefarah  not working as expected in v4 it gives me an error.
yq version 4.9.1

```./yq4 eval 'del(.docker::run_instance::instance.example2)' data.yaml```

output:-
Error: Parsing expression: Lexer error: could not match text starting at 1:14 failing at 1:15.
        unmatched text: "r"

**Comment by thatsk** [comment] 2021-05-17 13:24
can you tell me what's wrong with this why it's throwing an error?

**Comment by thatsk** [comment] 2021-05-18 08:35
@mikefarah  can you provide me how to resolve this error
?
