### ISSUE TITLE
Anchors not working

### ISSUE THREAD

**Issue by caub** [mikefarah/yq#178] opened 2018-09-24 10:14 UTC
```sh
yq r - <<EOF
serv:
  lol:
    <<: &s
      bar: ko
    foo: ok
  wat: *s
EOF

serv:
  lol:
    foo: ok
  wat:
    bar: ko

```

it should give

```sh
serv:
  lol:
    bar: ko
    foo: ok
  wat:
    bar: ko
```

**Comment by mikefarah** [comment] 2018-10-08 05:02
Yep can confirm, looks like its an issue in the underlying yaml library I'm using - and they won't fix it until v3 comes out.

https://github.com/go-yaml/yaml/issues/184#issuecomment-371859215

**Comment by cup** [comment] 2019-02-10 22:46
https://github.com/mikefarah/yq/issues/206

**Comment by cup** [comment] 2019-02-10 22:59
https://github.com/drone/drone/issues/2323
https://github.com/drone/drone-cli/pull/103
https://github.com/go-swagger/go-swagger/issues/1193
https://github.com/go-yaml/yaml/issues/184
https://github.com/go-yaml/yaml/issues/344
https://github.com/go-yaml/yaml/issues/91

https://github.com/mikefarah/yq/issues/178
https://github.com/mikefarah/yq/issues/206

**Comment by Trane9991** [comment] 2019-04-06 07:32
go-yaml.v3 is available [[blogpost here]](https://blog.ubuntu.com/2019/04/05/api-v3-of-the-yaml-package-for-go-is-available)!

**Comment by ssoerensen** [comment] 2019-06-26 08:56
Any update on this issue?

**Comment by thelangley** [comment] 2019-07-19 10:40
we're bumping into this too and have to use fun python scripts to work around this functionality.

Not a biggy but would be ace if it could follow anchors

**Comment by galindro** [comment] 2019-09-20 13:12
@mikefarah Do you have an ETA for fix this problem?

**Comment by mikefarah** [comment] 2019-09-20 13:32
The problem is that to use the v3 library I basically need to rewrite yq. Just don't have the time for that atm :(

**Comment by galindro** [comment] 2019-09-20 13:33
Ok man, I completely understand you. Take your time.

**Comment by jk2K** [comment] 2019-11-13 09:31
duplicate of https://github.com/mikefarah/yq/issues/264

**Comment by jk2K** [comment] 2019-11-13 09:32
> The problem is that to use the v3 library I basically need to rewrite yq. Just don't have the time for that atm :(

I will try to support this feature

**Comment by mikefarah** [comment] 2020-01-10 22:57
Just released a new version of yaml that fixes this - it's a pretty significant update so it's still in beta: https://github.com/mikefarah/yq/releases/tag/3.0.0-beta

**Comment by mikefarah** [comment] 2020-01-31 02:15
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1

**Closed by mikefarah** 2020-01-31 02:15 UTC
Labels: bug, yaml-v3
